# variables.tf

variable "konnect_personal_access_token" {
  description = "Personal access token for Konnect"
  type        = string
  sensitive   = true
}

variable "konnect_api_url" {
  description = "The Kong Konnect API URL to use."
  type        = string
  default     = "https://us.api.konghq.com"
}

variable "konnect_control_plane_id" {
  description = "The ID of the Konnect Control Plane"
  type        = string
}

variable "plugin_schema" {
  description = "The plugin's schema.lua as a string, generated by running 'jq -Rs '.' schema.lua'"
  type        = string
  default     = "return {\n  name = \"traceable\",\n  fields = {\n    {\n      config = {\n        type = \"record\",\n        fields = {\n          { ext_cap_endpoint = { type = \"string\", required = true } },\n          { allow_on_failure = { type = \"boolean\", required = true, default = true } },\n          { service_name = {type = \"string\", required = false, default = \"kong\"} },\n          { timeout = { type = \"number\", required = false, default = 500 } },\n        },\n      },\n    },\n  },\n}\n"
}